language: rust
rust:
#- stable
#- beta
- nightly
sudo: false
os:
- linux
cache:
  directories:
  - "$HOME/.cargo"
  - target
#matrix:
#  fast_finish: true
#  allow_failures:
#  - rust: nightly
env:
  matrix:
  - CARGO_FEATURES=
  - CARGO_FEATURES=qmp
  - CARGO_FEATURES=qga
  - CARGO_FEATURES="qga qmp"
  global:
  - CARGO_QUIET=
  - CARGO_INCREMENTAL=0
  - secure: kyxMAICkzUFxMJWi5x/5LhExM+EyoNQesj0myfr4DfNVv4R7NnkRhNSu+cFOKf49MYeAF52dCtl4mviuU3Izkvphr1G3MPT8LvOtgpBqqgVgb/XThACHWgv+nqI3+xWMXaIicJc6h19PTNevH6q+4ZTKcGWflLgIwnCOsFNmVL4KuvhAnuDjSvIdBuNswcp9r44BovoGrDUVdldfhT/vbMG9UTJHznJlg/g/CCj4cIiDiNwXSD9UUt2vW8rixYzvmKiYqlCYJpjU3joZw/3UzoWNJULh7hMh/UERcr7Mv9PQdotg3yzjssNZfAxhwxbWFqBzb7abhw+baM22MHmWq3hOfhg2CuakZWc13Jt3G6wK/OrFYOFodKCldVEddv/9lbSR4hu5pyDH3gaNEbtPjzuZzdE3P2/6C2LYVmHmop+JXAw+Wq23z8KIJhIHVhDxBd1y72mQsrL7yv1n9+q04ZwWT/1QNKHUMD5WgMpRZzp06kxL3h9XP2t6wZSnji1JExAPBZu199bgaKqPAqttW5V/mTfEitSzalEhu3FQyJVRxOuj4EC/ftcw8qGvcGQUnZF21ratWWTT8ljF/gXoe/kDh0e6neF5XTaQ1YX7u8MouEvfUVmlt3huVKy/EAwLGzUyRJyGPYZCEBwpl7rGlwZhdKfTFTT9EUR+9VdNgKU=
  - secure: bbbj04pr4kjEDTJZ/wED9sXmhRSoupFddsVo37S6+CLsmgssiD4lYTP1pyOoJ6Y0O1+6DE1l9a3dSexM/0VnnmuVuBExF1xzdlLRqsarTuDXkZjDa+ksuAMVDeb95dR3osq0TyDhAoXS+c7PdnbXHSKsJqPP//7mhDsWhHJhqAw/anIxBvLliYbxKV1mtiHoRuG+cbJe+lG74mltAJHn+DoPsh8gagqEQSUzF/VHpgQw5KO1U/xIk3xrFd2HAoyWvAt/PLRG81TiEeUFs1LDBrfwK+Ujyt2UtJDr3Q960QfO0sNO9+oqGHiwGK3capf9TY0h877p5IDUtPi8608/hzRsnf4o1aYAkFHbX/xUwLvv2HjLhRlzsfHBhX8epcEhIQcFhwzUQI4Wat0pt7i5a/RPyYYd3N4I1aLSGZ4/lr1G5dMPg10donL2j0uBfEKomxS8UARXzOeKoJ+rmc3jGhmw+WqwAtBonG0y1aZVaoJLoYK/FnNSxtuYcNq8tm/FEyUT5LC+2VsHcJn2+OIxSxhYwzeP5I0W3GzKa9RDNGA4s+nTHqilNCWW0i5EJdmDHqA7fLAiP202xOLuY24/XTsbQnWWEKCR5hOAR6sK4lzvCJdm2/bfVToWL2lriPH1zCT2BBK7X+57rhTHusTcfXrGSlOzZqPvFFycB5RYx3U=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.2.tar.gz | tar -xzC $HOME && . $HOME/ci-0.2/src
script:
- cd $TRAVIS_BUILD_DIR/qapi
- cargo test -p qapi
- cargo build -p qapi
- cd $TRAVIS_BUILD_DIR/tokio
- cargo test -p tokio-qapi
- cargo build -p tokio-qapi
- cd $TRAVIS_BUILD_DIR/parser
- CARGO_FEATURES= cargo test -p qapi-parser
- CARGO_FEATURES= cargo build -p qapi-parser
- cd $TRAVIS_BUILD_DIR/spec
- CARGO_FEATURES= cargo test -p qapi-spec
- CARGO_FEATURES= cargo build -p qapi-spec
- cd $TRAVIS_BUILD_DIR/codegen
- CARGO_FEATURES= cargo test -p qapi-codegen
- CARGO_FEATURES= cargo build -p qapi-codegen
- |
  if [[ $CARGO_FEATURES = *qga* ]]; then
    cd $TRAVIS_BUILD_DIR/qga
    CARGO_FEATURES= cargo test -p qapi-qga
    CARGO_FEATURES= cargo build -p qapi-qga
  fi
- |
  if [[ $CARGO_FEATURES = *qmp* ]]; then
    cd $TRAVIS_BUILD_DIR/qmp
    CARGO_FEATURES= cargo test -p qapi-qmp
    CARGO_FEATURES= cargo build -p qapi-qmp
  fi
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable && $CARGO_FEATURES = 'qga qmp'"
before_deploy:
- cd $TRAVIS_BUILD_DIR/qapi
- cargo doc -p qapi-parser
- cargo doc -p qapi-spec
- cargo doc -p qapi-codegen
- cargo doc -p qapi-qga
- cargo doc -p qapi-qmp
- cargo doc -p qapi
- cd $TRAVIS_BUILD_DIR/tokio
- cargo doc -p tokio-qapi
- cd $TRAVIS_BUILD_DIR/spec
- cargo package
- cd $TRAVIS_BUILD_DIR/parser
- cargo package
after_deploy:
- cd $TRAVIS_BUILD_DIR/spec
- cargo publish
- cd $TRAVIS_BUILD_DIR/parser
- cargo publish
- cd $TRAVIS_BUILD_DIR/codegen
- cargo publish
- cd $TRAVIS_BUILD_DIR/qga
- cargo publish
- cd $TRAVIS_BUILD_DIR/qmp
- cargo publish
- cd $TRAVIS_BUILD_DIR/tokio
- cargo publish
- cd $TRAVIS_BUILD_DIR/qapi
- cargo publish
